### ISSUE TITLE
scrolling invoices set params in url so we could get back to the list into the right place

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#101]
something like this http://scrollsample.appspot.com/items
or maybe this kind of idea http://blog.gesteves.com/2011/09/22/better-infinite-scrolling-with-the-html5-history-api/

**Comment by JoeZ99** [comment]
@peillis
This needs a little more coding than expected.

Our current infinite scrolling model is "forward only", i.e. the page only loads the items that are from a "next" page , not from a "previous" one, which is ok, because during a normal scrolling operation, all the previous content have been loaded before, but for this (getting back to the list into the right place), we need the infinite scrolling to work both ways, "prev" and "next". 

 - Say I've scrolled up to the third page in the listing, and the url is accordingly modified with that info (invoices?page=3 or invoices#3 or whatever)
  - Say we click on the first item of that position in the scroll, and go to item details. Then we click the back button, that points to the previously modified url (/items?page=3).
  - Only can think of two ways of getting back to the same position in the scroll
    - load the page with the 30 first results (assuming its 10 results per page) and a #page3 or something so we can present the user the portion of the page as it was when clicked
    - present only the page of results 30-40 and have infinite scrolling working for both previous results and next results.

**Comment by JoeZ99** [comment]
some more ideas
http://www.sitepoint.com/infinite-scrolling-rails-practice/

anyway, so far the cleanest solution is google's http://scrollsample.appspot.com/items

**Comment by JoeZ99** [comment]
I hereby declare this issue as closed.
