### ISSUE TITLE
What is the difference between siwapp and siwapp-sf1

### ISSUE THREAD

**Issue by lalop** [siwapp/siwapp#36]
Hello,
I just come to discover siwapp, I want to try it but I don't understand what's the difference  between all the siwapp apps.
Is sf2 died ?
Are siwapp-sf and siwapp the exact same app with different implementation ? Or is there some different functionnality ?

**Comment by carlosescri** [comment]
Hi,

- siwapp-sf1: Current stable version. Developed in Symfony 1.x. Anyone can contribute but no new features are planned (if we add any is because we currently use it).
- siwapp: We are migrating Siwapp to Ruby on Rails 4. This is the current dev version and once migrated, this will get any new improvements. Again, anyone is invited to contribute via pull requests. We use this to learn Ruby and Rails.
- siwapp-sf2: Our try to use Symfony 2 but we didn't like it, so it's currently abandoned.

**Comment by lalop** [comment]
Good to know,
What is the current status of the rails version compared to the sf1 one ?

**Comment by carlosescri** [comment]
Very alpha :-P

**Comment by lalop** [comment]
One last question, if I start to use siwapp-sf1 could I migrate to the siwapp-rails whithout lost my data ?

**Comment by carlosescri** [comment]
That's the idea. As we develop the new version we update a script to migrate from the old one.

**Comment by lalop** [comment]
:+1:  tiptop
thank you
