### ISSUE TITLE
Dashboard: generation of totals

### ISSUE THREAD

**Issue by carlosescri** [siwapp/siwapp#42]
Should not be done as in v1 version!!! (in login page a very high-cost query is done to generate invoices).

Suggestions:

- Some kind of cron that executes a rake task for that?
- Ask in Dashboard, if user confirms invoices generation, open a new small window and generate invoices in chunks controlled via AJAX. If user closes that window, pending recurring invoices will be notified again in Dashboard.
- A version of the previous one: Add a section in the UI that notifies that there are pending invoices to be generated. That section is a partial displayed in all pages. When the user starts the process, that section contains the status of the process and controls it, performing new AJAX calls to generate invoices until all of them have been generated.
- ...

Seems a bit complicated but the way it's currently done is very high-cost (I'd added an index and increased memory in one of our servers, not everybody has this possibility).

More research needed, of course.

**Comment by JoeZ99** [comment]
I think
https://github.com/brandonhilkert/sucker_punch
it's worth a try

Essentially is a async processor which does not need any extra worker. There are plenty of background processors in rails (https://www.ruby-toolbox.com/categories/Background_Jobs), but most of them requires to start a "job server", a secondary worker which receives the jobs requests and process them. That usually means an extra $35 in you heroku monthly bill.

Sucker punch is built to avoid that (http://brandonhilkert.com/blog/why-i-wrote-the-sucker-punch-gem/). Looks simple, and comes with no extra heroku costs. I guess it's not meant for rich queue management or giant queues, but I think It'll work just fine in our use case

With this, we can do it "celery style":

```ruby
class GeneratePendingInvoicesJob
  include SuckerPunch::Job

  def perform()
    ActiveRecord::Base.connection_pool.with_connection do
      # do stuff
    end
  end
end
```

and in the controller
```ruby
GeneratePendingInvoicesJob.new.async.perform()
```

**Comment by carlosescri** [comment]
I like that!

Only remember not to do checks in the login page. Better in the dashboard, and ensure there are proper indices in the table for the query to be done fast. Currently Siwapp in PHP uses a lot of resources for that single query for everyone that access the login page.

**Comment by JoeZ99** [comment]
I'm confused , are you talking about the "read only" query that you should do to check whether or not there are pending invoices, or the "modify data" query that you have to do to actually generate them.

I was thinking, since we're going background with this , we may as well generate the invoices using a less expensive and slower method, but I was hoping that the query "just to see" if  there are pending invoices (i.e. invoices that should be generated already from the recurring but are not) would be simple.

**Comment by JoeZ99** [comment]
I'm confused , are you talking about the "read only" query that you should do to check whether or not there are pending invoices, or the "modify data" query that you have to do to actually generate them.

I was thinking, since we're going background with this , we may as well generate the invoices using a less expensive and slower method, but I was hoping that the query "just to see" if  there are pending invoices (i.e. invoices that should be generated already from the recurring but are not) would be simple.

**Comment by carlosescri** [comment]
Well, don't do whatever is being done in siwapp-sf1 in the login page (I think it's an expensive read only query because there's a button to generate pending invoices for the logged-in user).

**Comment by JoeZ99** [comment]
we got it all wrong.

what's done in the siwapp login page is calculating totals for today , and that indeed is a very expensive query.

regarding pending invoices generation, I have no recollection of how "expensive" it used to be, but I'm sure it was always done via the "generate pending invoices" button.

So I guess we should rename this issue to "dashboard: calculate totals ", and consider using this same tool to generate totals.

   - totals generation is triggered (as a background process) in the login page.
   - in the dashboard, there is a clock or the like instead of totals. some ajax polling to update it

**Comment by carlosescri** [comment]
Qué memoria la mía...

**Comment by peillis** [comment]
What exactly is the point of calculating totals for a day? Because I think those totals depends on the date range selected which the user can change pretty easily.

**Comment by JoeZ99** [comment]
sorry, I just jumped too fast to conclusions. It's not "totals per day" it's more like "assure that every total_gross, total_net, tlotal_tax" and the like fields of the invoices are up to date . so those calculations you talk about are easier (just what we do in siwapp-sf1)

**Comment by JoeZ99** [comment]
sorry, I just misread the siwapp code, . It's not "totals per day" it's more like "assure that every total_gross, total_net, tlotal_tax" and the like fields of the invoices are up to date, so those calculations you mention are easier (just what we do in siwapp-sf1)

**Comment by peillis** [comment]
Right, but I think that that being updated should be a matter of the invoice edition, not a background process

**Comment by JoeZ99** [comment]
of course. but however in siwapp-sf1 this is what is done. Apart from the "totals" fields being updated at the actions layer every time an inoivce is saved or a payment is added (and that should be done with it), in the login page, all the invoices are "synced with their totals" again.

I just thought there was a reason for this. maybe it happened too often that totals weren't "synced", I don't know...I just got carried away by this issue.

anyway we could just do nothing  and wait for the issue to show, if it ever does.

**Comment by carlosescri** [comment]
Ok, I close the issue for the moment. Just remember: don't perform high cost calculations in the request/response flow.
