### ISSUE TITLE
check why customer_spec it's not working

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#72]
https://github.com/siwapp/siwapp/blob/master/spec/models/customer_spec.rb

**Comment by JoeZ99** [comment]
turns out it was some super hidden and super weird behavior. 

in https://github.com/siwapp/siwapp/commit/22bdbfb8e837f1cb894ca1850307da8afc1c9649, the `set_amounts` method is called also on the `after_initialize` callback.

Due to some rails black magic, setting the amounts after **object initialization**, makes the corresponding amount attribute to act like the if values that were set during the `set_amounts` method call were obtained from the database, leading `ActiveRecord` to think that those attributes haven't been altered at all, which leads to miss those field names when effectively updating the corresponding database record (those fields are not updated since ruby thinks the haven't been changed).

In a nutshell (i'm finding this hard to explain in English, but still going to do it, because this little moth*@(!!er have been eating my nights with no mercy at all).

  - The `ActiveRecord` framework, when saving the model only updates at the database row the changed model attributes. In order to do that , it needs to track attribute changes
  - It probably starts tracking attribute changes some time **after** model initialization. We're changing the amount attributes more or less during model initialization, so it's possible to think that by the time those attributes are changed , `ActiveRecord` hasn't started tracking them yet.
  - Et vuala! since `ActiveRecord` thinks those attribs are not changed, they are no effectively updated at the database row.


As you can see in the commit, (check the corresponding remote branch), the simplest solution I could find was to manually set those attribs as changed if needed.

But I wonder how badly we need to call `set_amounts` during object initialization :

  - Theoretically , those quantities are persisted when the model is saved, so it shouldn't be necessary to recalculate them on mode initialization, that looks a lot like a "just in case" sort of method, and precisely because I tend to abuse their use, I don't think it's a good pattern.
  - we're effectively recalculating amounts every time the model is instantiated, each time those are listed, those calculations are made for every instance. What is the point of the saved amounts them? I know for global calculations they're still useful, but since they're there, we may as well take advantage of that and use them instead of recalculating them if we have the chance.

**Comment by JoeZ99** [comment]
I'll leave the ticket open for a few days, hoping for your input.

**Comment by JoeZ99** [comment]
I'll leave the ticket open for a few days, hoping for your input.

**Comment by peillis** [comment]
I don't know the problems you're facing, but as you see in the commit a lot of set_amounts were deleted. But if you think that should be changed because doesn't work right it's up to you.
