### ISSUE TITLE
a customer shouldn't be allowed to delete if there are invoices related

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#82]

**Comment by JoeZ99** [comment]
@peillis, this is done, but wouldn't it be better if this restriction apply only when the customer has pending invoices?  I'm thinking on a scenario in which a user may want to keep all the closed invoices although she want to delete some particular customer.

**Comment by peillis** [comment]
yep, that makes sense. But the customer id would be anyway on the invoices. Maybe the best option would be to not real delete it from the table, but mark it as deleted and not show it anymore.

**Comment by JoeZ99** [comment]
The inovice contains itself all fields identifying customer (email, identifcation, contact_person), so if it's not problematic for the system, I don't see why invoices with an empty customer_id should be a problem. I would leave it just like that. Assuming the system keeps working right, which I hope, because the coupling between invoice and customer is not that tight, is it?

**Comment by peillis** [comment]
you're right
