### ISSUE TITLE
change of plans with the delete strategy

### ISSUE THREAD

**Issue by peillis** [siwapp/siwapp#96]
don't remove anything from database, just mark them as deleted

**Comment by JoeZ99** [comment]
this would be for
  - invoices
  - recurring invoices
  - customers

but nothing else, right? (items, taxes)

**Comment by JoeZ99** [comment]
any particular reason?

**Comment by JoeZ99** [comment]
actually, it would be simpler if we do it with everything https://github.com/rubysherpas/paranoia

**Comment by peillis** [comment]
Let's do it with everything

**Comment by JoeZ99** [comment]
regarding this.

  - items and payments are to be soft deleted too, otherwise it wouldn't make much sense to have invoices soft deleted if when recovering them, their items/payments can't be.

  - however, during the creation/edition of an invoice, one may create bogus items or payments, and logically one would want to remove them. If we "soft delete" them, then if the invoice is soft deleted we couldn't tell which soft deleted items are from the "final" soft deleted invoice and which are just a byproduct of the invoice editing process.

  - The solution that comes to mind so far is that for the items/payments operations that are to be performed on an invoice , the `destroy` operations are for rea.

**Comment by JoeZ99** [comment]
final implementation:
  - when adding or removing items or payments during normal invoicing operations, those are really removed, at the `after_update` callback
  - when destroying an invoice or recurring invoice, items and payments are soft-deleted
  - invoices and recurring implement a `back_from_death` method that restore the invoice and its items and payments
